// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXt3awlcNC3VQw5NmYOr0oSQTml3FMMPM',
    appId: '1:475710754618:web:8d42b64110def70f51ca03',
    messagingSenderId: '475710754618',
    projectId: 'pet-clinic-17f05',
    authDomain: 'pet-clinic-17f05.firebaseapp.com',
    storageBucket: 'pet-clinic-17f05.firebasestorage.app',
    measurementId: 'G-83N700S3DM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlzAQlbfPya0J46Mzi-NizoIAS_j7xtYM',
    appId: '1:475710754618:android:cd9d65d1c4d9304151ca03',
    messagingSenderId: '475710754618',
    projectId: 'pet-clinic-17f05',
    storageBucket: 'pet-clinic-17f05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWH5UdFUwZRjE0dvk3Z7um1TpNLVZaB74',
    appId: '1:475710754618:ios:51884228a534ea4451ca03',
    messagingSenderId: '475710754618',
    projectId: 'pet-clinic-17f05',
    storageBucket: 'pet-clinic-17f05.firebasestorage.app',
    iosBundleId: 'com.example.petClinic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWH5UdFUwZRjE0dvk3Z7um1TpNLVZaB74',
    appId: '1:475710754618:ios:51884228a534ea4451ca03',
    messagingSenderId: '475710754618',
    projectId: 'pet-clinic-17f05',
    storageBucket: 'pet-clinic-17f05.firebasestorage.app',
    iosBundleId: 'com.example.petClinic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXt3awlcNC3VQw5NmYOr0oSQTml3FMMPM',
    appId: '1:475710754618:web:b442e5223ef604fd51ca03',
    messagingSenderId: '475710754618',
    projectId: 'pet-clinic-17f05',
    authDomain: 'pet-clinic-17f05.firebaseapp.com',
    storageBucket: 'pet-clinic-17f05.firebasestorage.app',
    measurementId: 'G-P0BZRDZEPS',
  );
}
